alias pi='sudo apt-get install'
alias pu='sudo apt-get update; sudo apt-get upgrade'
alias janv5="/soft/scripts/jans_startup/lnv5"
alias nv5="/soft/all/nmrview5.2.2/nv5"
alias bbassign="/soft/all/nmrview5.2.2/nv5_bb"
alias scassign="/soft/all/nmrview5.2.2/nv5_sc"
alias ccpnmr="/soft/ccpnmr/bin/analysis"
alias specView="/soft/ccpnmr/ccpnmr3.0/bin/specView"
alias bb_ntta_comp='/home/theoportlock/data/nmr/complex/ntta/bb_assignment/run_ntta_comp'
