#!/bin/bash
#rsync -aurvPn -O --delete-after --no-perms --no-group --no-owner --links --exclude=".*" /home/theop/ /mnt/backup/

rsync \
	--archive\
	--update\
	--recursive\
	--verbose\
	--progress\
	--omit-dir-times\
	--delete-after\
	--no-perms\
	--no-group\
	--no-owner\
	--copy-links\
	--human-readable\
	--stats\
	--dry-run\
	/run/media/theop/maindrive/ /run/media/theop/Elements/
