#!/bin/bash

while getopts ":a:" opt: do
	case $opt in
		a)
			echo "-a was triggered" >&2
			;;
		\?)
			echo "invalid flag" >&2
			exit 1
			;;
		:)
			echo "needs an argument" >&2
			exit 1
			;;
	esac
done
