#!/bin/bash
fullnam="thesis.tex"
nam=$(echo $fullnam | cut -f 1 -d  '.')
cd ~/thesis/ &&
pdflatex $fullnam && 
makeindex -s $nam.ist -t $nam.glg -o $nam.gls $nam.glo &&
bibtex $nam && 
pdflatex $fullnam && 
pdflatex $fullnam && 
sh ~/system/scripts/adobe $nam.pdf 
