#!/usr/bin/env python
import networkx as nx
import pandas as pd
import sys

filename = sys.argv[1]
strip=filename[:filename.find(".")]+".dot"
df = pd.read_csv(filename)
Graphtype = nx.Graph()
G = nx.from_pandas_edgelist(df, edge_attr='weight', create_using=Graphtype)
nx.nx_agraph.write_dot(G,strip)
