#!/bin/bash
nam=$(echo $1 | cut -f 1 -d  '.')
#dot -Tsvg -Kcirco -o ${nam}.svg $1 && feh --conversion-timeout 1 ${nam}.svg &
dot -Tsvg -Kcirco -o ${nam}.svg $1
#can also use the -K<format> where format is
#neato
#fdp
#sfdp
#twopi
#circo
