#!/bin/bash
# names = lspc_tmhrhr, ntta, lspd_n0
# previous run = 17,21,35

nam="ntta" &&
run=22 &&
# prevrun=$(($run-1))
# scp -r ~/data/nmr/${nam}/ccpnmr/run${run}analysis/ tportlock@tportlock.nmrbox.org:/home/nmrbox/tportlock/aria/${nam}/
# ssh tportlock@tportlock.nmrbox.org "cd aria/$nam && cp run${prevrun}.xml run$run.xml && mv run$prevrun.xml run${prevrun}analysis run$prevrun.log run$prevrun && sed -i 's/run${prevrun}/run${run}/g' run${run}.xml && sed -i 's/\"${prevrun}\"\ file_root/\"${run}\"\ file_root/g' run$run.xml && sed -i 's/run${prevrun}analysis/run${run}analysis/g' run${run}.xml"
#&& aria2 -s run${run}.xml
#; aria2 --output=run${run}.log run${run}.xml > /dev/null 2>&1 &" &&
scp -r tportlock@tportlock.nmrbox.org:/home/nmrbox/tportlock/aria/${nam}/run${run}/structures/refine/  &&
mv run${run}analysis ~/data/nmr/${nam}/ccpnmr/run${run}analysisR &&
mv it8 ~/data/nmr/${nam}/ariastructures/run${run}structures
