#!/bin/bash
cd /tmp
wget -O rclone-current-linux-amd64.zip https://downloads.rclone.org/rclone-current-linux-amd64.zip
unzip rclone-current-linux-amd64.zip
cp rclone-v*/rclone /usr/sbin; rm -rf rclone*
mkdir ~/.config
mkdir ~/.config/rclone
cat > ~/.config/rclone/rclone.conf << EOF
###### PASTE RCLONE CONFIG HERE ######
[Google]
type = drive
client_id =
client_secret =
token = {"access_token":"ABCD","token_type":"Bearer","refresh_token":"EFGH","expiry":"2017-01-01T00:13:24.778083454-07:00"}
####### OVERWRITE ABOVE WITH YOUR WORKING CONFIG #######
EOF
SERVER=$(hostname)
SERVER=${SERVER,,}
tar -c -f /tmp/${SERVER}-backup.tar.gz file1 /etc/file2 /home/myuser1 /home/myuser2
rclone copy /tmp/${SERVER}-backup.tar.gz Google:/Backups -q --checksum --drive-chunk-size=64M
rm /tmp/${SERVER}-backup.tar.gz
