#!/bin/bash
name=$(sed -n -e 's/^name=//p' ~/.computer)
curr=~/system/computers/$name/curr_rcfiles
[ -d "$curr" ] && rm -r $curr
mkdir $curr &&
cp -r ~/.?*rc $curr
cp -r ~/.X* $curr
cp -r ~/.computer $curr
mkdir -p $curr/.config/i3 && cp -r ~/.config/i3/config $curr/.config/i3
cp -r ~/.i3status.conf $curr
cp ~/.bash_profile $curr
diff -rq $curr ~/system/computers/$name/rcfiles
urxvt --noclose -e dimdiff
