#!/bin/bash
sudo pacman --noconfirm -Syu
yay --noconfirm -Syu
pip freeze — local | grep -v ‘^\-e’ | cut -d = -f 1 | xargs -n1 pip install -U
git -C ~/thoughts pull ;
git -C ~/tis pull ;
git -C ~/tester pull ;
git -C ~/proteintools pull ;
git -C ~/thesis pull ;
git -C ~/notes pull ;
git -C ~/todo pull
