#!/bin/bash
yay --noconfirm -Syu
pip install --upgrade pip
pip list --outdated --format=freeze | grep -v ‘^\-e’ | cut -d = -f 1 | xargs -n1 pip install -U
find . -type d -name .git -exec sh -c "cd \"{}\"/../ && pwd && git pull"
